name: VisualClaims
main: com.example.visualclaims.VisualClaims
version: 1.0.0
api-version: 1.20
depend: [dynmap]
author: e1ixyz

commands:
  createtown:
    description: Create a town
    usage: /createtown <name>
    permission: visclaims.createtown
  deletetown:
    description: Delete your town
    usage: /deletetown
    permission: visclaims.deletetown
  claimchunk:
    description: Claim the current chunk
    usage: /claimchunk
    permission: visclaims.claim
  unclaim:
    description: Unclaim the current chunk
    usage: /unclaim
    permission: visclaims.unclaim
  autoclaim:
    description: Toggle autoclaim for chunks
    usage: /autoclaim
    permission: visclaims.autoclaim
  settownname:
    description: Rename your town
    usage: /settownname <name>
    permission: visclaims.setname
  settowncolor:
    description: Set your town's color (vanilla color names)
    usage: /settowncolor <color>
    permission: visclaims.setcolor
  settowndesc:
    description: Set your town description
    usage: /settowndesc <text>
    permission: visclaims.setdesc
  claiminfo:
    description: Show info about your town
    usage: /claiminfo
    permission: visclaims.claiminfo
  claimhistory:
    description: Show claim history for the current chunk
    usage: /claimhistory
    permission: visclaims.history
  claim:
    description: Root command for claim help
    usage: /claim help
    permission: visclaims.help
  claimlimit:
    description: Show playtime-based claim limit
    usage: /claimlimit [player]
    permission: visclaims.claimlimit
  adjustclaims:
    description: "Admin: add or remove bonus claim slots"
    usage: /adjustclaims <player> <add|remove> <amount>
    permission: visclaims.admin
  towninvite:
    description: Invite a player to your town
    usage: /towninvite <player>
    permission: visclaims.invite
  jointown:
    description: Accept a town invitation
    usage: /jointown <town>
    permission: visclaims.join
  townmembers:
    description: Show members in your town
    usage: /townmembers
    permission: visclaims.members
  removemember:
    description: Remove a member from your town
    usage: /removemember <player>
    permission: visclaims.kick
  towns:
    description: Public listing of towns
    usage: /towns
    permission: visclaims.towns
  towninfo:
    description: Public town details
    usage: /towninfo <town>
    permission: visclaims.towninfo
  autohistory:
    description: Toggle automatic chunk history feed
    usage: /autohistory
    permission: visclaims.autohistory
  war:
    description: Declare or resolve war with another town
    usage: /war <town>
    permission: visclaims.war
  alliance:
    description: Manage alliances with other towns
    usage: /alliance <town>|accept <town>|remove <town>
    permission: visclaims.alliance
  warmode:
    description: "Admin: toggle global war mode and scoreboards"
    usage: /warmode <on|off>
    permission: visclaims.warmode
  warscoreboard:
    description: Toggle your war scoreboard view
    usage: /warscoreboard
    permission: visclaims.warscoreboard
  claimadmin:
    description: Show admin-only claim commands
    usage: /claimadmin
    permission: visclaims.adminhelp

permissions:
  visclaims.createtown:
    description: Allows creating a town
    default: true
  visclaims.deletetown:
    description: Allows deleting your town
    default: true
  visclaims.claim:
    description: Allows claiming chunks
    default: true
  visclaims.unclaim:
    description: Allows unclaiming chunks
    default: true
  visclaims.autoclaim:
    description: Allows toggling autoclaim
    default: true
  visclaims.setname:
    description: Allows renaming your town
    default: true
  visclaims.setcolor:
    description: Allows changing your town color
    default: true
  visclaims.setdesc:
    description: Allows setting your town description
    default: true
  visclaims.claiminfo:
    description: Allows using /claiminfo to view your town details
    default: true
  visclaims.history:
    description: Allows using /claimhistory to view chunk history
    default: true
  visclaims.help:
    description: Allows using /claim help to view all claim commands
    default: true
  visclaims.claimlimit:
    description: Allows using /claimlimit to view claim limits (admins can target others)
    default: true
  visclaims.invite:
    description: Allows inviting players to a town
    default: true
  visclaims.join:
    description: Allows accepting a town invitation
    default: true
  visclaims.members:
    description: Allows viewing members in your town
    default: true
  visclaims.kick:
    description: Allows removing members from your town
    default: true
  visclaims.towns:
    description: Allows viewing the public town list
    default: true
  visclaims.towninfo:
    description: Allows viewing public town information
    default: true
  visclaims.autohistory:
    description: Allows toggling autohistory
    default: true
  visclaims.war:
    description: Allows declaring war with other towns (owners only)
    default: true
  visclaims.alliance:
    description: Allows managing alliances (owners only)
    default: true
  visclaims.warmode:
    description: Allows toggling global war mode
    default: op
  visclaims.warscoreboard:
    description: Allows toggling personal war scoreboard
    default: true
  visclaims.adminhelp:
    description: Allows viewing admin claim help
    default: op
  visclaims.admin:
    description: Bypass limits and manage towns for testing/admin purposes
    default: op
